### ISSUE TITLE
感觉可以把脚本挂到云服务器

### ISSUE THREAD

**Issue by sakurasep** [polosec/qfnuAutoTemperatureSubmit#1]
正好有一台阿里云服务器，试试挂到服务器每天定时执行

**Comment by SakuraLoveSmile** [comment]
在云服务器执行出现了以下错误，是什么原因呢？
![](https://gitee.com/sakurasep/pictures/raw/master/chevereto/2021011603.jpg)

**Comment by polosec** [comment]
就是为了挂crontab而做的。

**Comment by polosec** [comment]
> 在云服务器执行出现了以下错误，是什么原因呢？
> ![](https://camo.githubusercontent.com/8727b3b7b28a9a763702e47cba699358a31bcecb06bd39634733d3d8f6f124a0/68747470733a2f2f67697465652e636f6d2f73616b7572617365702f70696374757265732f7261772f6d61737465722f63686576657265746f2f323032313031313630332e6a7067)

需要你先自己在手机上定位 提交体温 获得到数据后才能使用脚本自动提交。

**Comment by SakuraLoveSmile** [comment]
ok 已经定位到原因了，现在是挂在服务器上，每天自动执行。
师哥🐂
